### ISSUE TITLE
librespot panics with subscription terminated

### ISSUE THREAD

**Issue by cortegedusage** [plietar/librespot#185] opened 2017-05-14 05:55 UTC
librespot panics with;
thread 'main' panicked at 'subscription terminated', /build/arm-unknown-linux-gnueabihf/release/build/librespot-376aadb7929f1a50/out/lib.rs:615
note: Run with `RUST_BACKTRACE=1` for a backtrace.

it's only with my wife's account which is part of our familly account, mine and others are working fine.
any idea's?

**Comment by cortegedusage** [comment] 2017-05-14 06:15
btw the account is working well in both ios app and windows app, so it is a premium account.

**Comment by plietar** [comment] 2017-05-15 14:51
Thanks for bringing up this issue.
`subscription terminated` is likely to be talking about an internal channel's subscription, which are used within librespot to communicate between threads, nothing to do with your Spotify account subscription.

Could you run librespot with the `RUST_BACKTRACE=1` environment variable, and the `--verbose` command line argument and post the full log please ?

**Comment by cortegedusage** [comment] 2017-05-15 14:57
Thanks for the reply.
Is It simply a matter of typing rust_backtrace=1 from the command line?
I'll try It maybe tonight.


Op 15 mei 2017 4:51 p.m. schreef "Paul Liétar" <notifications@github.com>:

Thanks for bringing up this issue.
subscription terminated is likely to be talking about an internal channel's
subscription, which are used within librespot to communicate between
threads, nothing to do with your Spotify account subscription.

Could you run librespot with the RUST_BACKTRACE=1 environment variable, and
the --verbose command line argument and post the full log please ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/plietar/librespot/issues/185#issuecomment-301499380>,
or mute the thread

**Comment by plietar** [comment] 2017-05-15 15:04
Yes, run librespot like this : 
```
RUST_BACKTRACE=1 path/to/librespot --name NAME --verbose ARGS...
```

**Comment by sashahilton00** [comment] 2017-05-15 15:06
You're going to want to use <code>export RUST_BACKTRACE=1</code>. Then run librespot.

**Comment by angerrit** [comment] 2017-05-15 16:23
I got the same issue. 

```
 export RUST_BACKTRACE=1
 librespot -v -n Test --backend pulseaudio 
```

```
INFO:librespot: librespot d95c0b3 (2017-04-13). Built on 2017-04-14.
DEBUG:librespot::authentication::discovery: Post "/" {}
INFO:librespot::session: Connecting to AP "gew1-accesspoint-a-dl4f.ap.spotify.com:4070"
INFO:librespot::session: Authenticated as " [...] " !
DEBUG:librespot::session: new Session[0]
DEBUG:librespot::spirc: new Spirc[0]
DEBUG:librespot::mercury: new MercuryManager
DEBUG:librespot::player: new Player[0]
DEBUG:librespot::audio_backend::pulseaudio: Using PulseAudio sink
DEBUG:librespot::session: Session[0] strong=3 weak=2
thread 'main' panicked at 'subscription terminated', librespot-git/src/librespot/target/release/build/librespot-017e4995ab345768/out/lib.rs:615
stack backtrace:
   1: 0x54ef75c3 - <unknown>
   2: 0x54efbd2f - <unknown>
   3: 0x54efb7ef - <unknown>
   4: 0x54efc223 - <unknown>
   5: 0x54c07cdf - <unknown>
   6: 0x54c72a5b - <unknown>
   7: 0x54be939b - <unknown>
   8: 0x54f033c7 - <unknown>
   9: 0x54efc8cf - <unknown>
  10: 0x76cc98bb - __libc_start_main
DEBUG:librespot::spirc: drop Spirc[0]
DEBUG:librespot::player: drop Player[0]
DEBUG:librespot::session: drop Session[0]
DEBUG:librespot::mercury: drop MercuryManager
DEBUG:librespot::session: drop Dispatch
```

I don't know if this is really helpfull.. I did not do any updates since it was working..

Thanks,
Jan

**Comment by mgmeedendorp** [comment] 2017-05-15 16:53
I also have the same issue since last weekend.

```
INFO:librespot: librespot 30bdcaf (2017-04-29). Built on 2017-05-04.
WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
INFO:librespot::session: Connecting to AP "gew1-accesspoint-a-4ll6.ap.spotify.com:4070"
INFO:librespot::session: Authenticated as "<username>" !
DEBUG:librespot::session: new Session[0]
DEBUG:librespot::spirc: new Spirc[0]
DEBUG:librespot::mercury: new MercuryManager
DEBUG:librespot::player: new Player[0]
DEBUG:librespot::session: Session[0] strong=3 weak=2
INFO:librespot::session: Country: "NL"
DEBUG:librespot::audio_backend::pulseaudio: Using PulseAudio sink
thread 'main' panicked at 'subscription terminated', /home/osmc/librespot/target/release/build/librespot-6d6a71d2e5f5cb52/out/lib.rs:614
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
   6: <librespot::spirc::SpircTask as futures::future::Future>::poll
   7: librespot::main
   8: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
   9: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  10: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  11: __libc_start_main
DEBUG:librespot::spirc: drop Spirc[0]
DEBUG:librespot::player: drop Player[0]
DEBUG:librespot::session: drop Dispatch
DEBUG:librespot::session: drop Session[0]
thread '<unnamed>' panicked at 'cannot access stderr during shutdown', /checkout/src/libcore/option.rs
```

Hope it's helpful

**Comment by markubiak** [comment] 2017-05-15 17:07
Yup.  Same issue, same backtrace, same timeframe.  I'm thinking Spotify had some serious backend change happen.  Note that spotify-connect-web still does work for me, which is odd.

Just gonna put this out there, it's an excerpt from the [libspotify page](https://developer.spotify.com/technologies/libspotify/):  
> Please note that we have removed the LibSpotify binaries from our website in an effort to phase out the usage of this deprecated library. LibSpotify has been considered deprecated since 2015 and will be shut down in 2017, so we want to ensure that all developers’ efforts and attention are focused on newer and better APIs that we actively support and maintain. These APIs include the Web API, iOS and Android SDKs, and upcoming embedded libraries for Windows, Mac OS X and Linux. More information regarding upcoming libraries will be provided in the coming months.

Based on this information, I would assume that this means libspotify APIs (the ones reverse engineered here) have been dropped.  But spotify-connect-web uses the same API and is still working?  I'd be amazed if Spotify specifically went after this project, as I don't think it harms anything...

**Comment by sashahilton00** [comment] 2017-05-15 17:12
the apis libspotify uses are no different to the once the Spotify clients use, and neither are the the ones librespot uses. Paul mentioned earlier that the subscription terminated message is a bug in librespot.

**Comment by markubiak** [comment] 2017-05-15 19:58
Alright, that's a bit reassuring at least.  Rather odd that it randomly appeared for several users with previously working binaries out of essentially nowhere.  My logs are pretty much identical but if there's any extra information I could provide please let me know.

**Comment by plietar** [comment] 2017-05-15 20:05
Thanks for the detailed reports. I can't reproduce it yet but I'm looking into it.

@markubiak What does the `Connecting to AP` line say at the start of the log ? I'm thinking Spotify might have made a small change to the protocol which is incompatible with my implementation, and it's rolling out to servers incrementally.

**Comment by cortegedusage** [comment] 2017-05-15 20:29
If It would help i could give you the credentials of my wife's account she
is hardly using It...

Op 15 mei 2017 10:05 p.m. schreef "Paul Liétar" <notifications@github.com>:

**Comment by plietar** [comment] 2017-05-15 20:59
I've pushed a commit which *might* fix it, and one which adds more debug information to the log.
Could you please give it a try ?

**Comment by markubiak** [comment] 2017-05-15 21:07
Hi Paul,

Here's my backtrace, which indicates that the server is "guc3-accesspoint-a-wmnz.ap.spotify.com".  I am in the Eastern US, if that helps.  Repetitive tests connected to "guc3-accesspoint-a-4nls.ap.spotify.com", "guc3-accesspoint-a-k7r9.ap.spotify.com", etc.

```
RUST_BACKTRACE=1 librespot -n "TESTING" -v
INFO:librespot: librespot 871e9e8 (2017-03-26). Built on 2017-04-13.
WARN:mdns::fsm: error sending packet Error { repr: Os { code: 99, message: "Cannot assign requested address" } }
DEBUG:librespot::authentication::discovery: Post "/" {}
INFO:librespot::session: Connecting to AP "guc3-accesspoint-a-wmnz.ap.spotify.com:4070"
INFO:librespot::session: Authenticated as "markubiak" !
DEBUG:librespot::session: new Session[0]
DEBUG:librespot::spirc: new Spirc[0]
DEBUG:librespot::mercury: new MercuryManager
DEBUG:librespot::player: new Player[0]
INFO:librespot::audio_backend::alsa: Using alsa sink
DEBUG:librespot::session: Session[0] strong=3 weak=2
thread 'main' panicked at 'subscription terminated', /home/travis/build/herrernst/librespot/target/arm-unknown-linux-gnueabihf/release/build/librespot-cbf31f11fa905ab0/out/lib.rs:615
stack backtrace:
   1: 0x54f1675b - std::sys::imp::backtrace::tracing::imp::write::h6e3058ba9f483d85
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2: 0x54f1aef3 - std::panicking::default_hook::{{closure}}::h6573be427de316b7
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:351
   3: 0x54f1a987 - std::panicking::default_hook::h227ecb2b238172e9
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:367
   4: 0x54f1b3e7 - std::panicking::rust_panic_with_hook::h2b1e04abef091579
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:555
   5: 0x54c19453 - std::panicking::begin_panic::h0e79edc1246bda43
   6: 0x54c8456b - <librespot::spirc::SpircTask as futures::future::Future>::poll::haee5d868d80d480f
   7: 0x54bf5c3b - librespot::main::hdd6ca9936aaf6545
   8: 0x54f221f3 - __rust_maybe_catch_panic
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libpanic_unwind/lib.rs:98
   9: 0x54f1ba93 - std::rt::lang_start::hadd6e99f3c8b00a8
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panicking.rs:436
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/panic.rs:361
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/rt.rs:57
  10: 0x76cf3293 - __libc_start_main
DEBUG:librespot::spirc: drop Spirc[0]
DEBUG:librespot::player: drop Player[0]
DEBUG:librespot::session: drop Session[0]
DEBUG:librespot::mercury: drop MercuryManager
DEBUG:librespot::session: drop Dispatch
```
My desktop and raspberry pi both experience the same issue in an identical fashion.  I'll try the new commit and also try a VPN to somewhere in Europe.

**Comment by mgmeedendorp** [comment] 2017-05-15 21:32
It seems like I'm getting the same error with the latest update. I'm in the Netherlands if that is relevant.


```
INFO:librespot: librespot 7c237c7 (2017-05-15). Built on 2017-05-15.
WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
INFO:librespot::session: Connecting to AP "gew1-accesspoint-a-0cpb.ap.spotify.com:4070"
INFO:librespot::session: Authenticated as "<username>" !
DEBUG:librespot::session: new Session[0]
DEBUG:librespot::spirc: new Spirc[0]
DEBUG:librespot::mercury: new MercuryManager
DEBUG:librespot::player: new Player[0]
DEBUG:librespot::audio_backend::pulseaudio: Using PulseAudio sink
DEBUG:librespot::session: Session[0] strong=3 weak=2
INFO:librespot::session: Country: "NL"
thread 'main' panicked at 'subscription terminated', /home/osmc/librespot/target/release/build/librespot-6d6a71d2e5f5cb52/out/lib.rs:614
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
   6: <librespot::spirc::SpircTask as futures::future::Future>::poll
   7: librespot::main
   8: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
   9: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  10: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  11: __libc_start_main
DEBUG:librespot::spirc: drop Spirc[0]
DEBUG:librespot::player: drop Player[0]
DEBUG:librespot::session: drop Session[0]
DEBUG:librespot::mercury: drop MercuryManager
DEBUG:librespot::session: drop Dispatch
```

**Comment by cortegedusage** [comment] 2017-05-15 21:38
I don't think the location is the issue.
I can listen wih my own account, but with my wife's account librespot
crashes.

Op 15 mei 2017 11:32 p.m. schreef "Maurice Meedendorp" <
notifications@github.com>:

**Comment by markubiak** [comment] 2017-05-15 21:50
I'm also getting that it's not location dependent, VPN has no effect.  Most recent commit sees no change from previous behavior.

**Comment by plietar** [comment] 2017-05-15 21:51
@cortegedusage I might take you up on your offer of using your account. If you want to change your password and send me your credentials to lietarp@gmail.com that would be awesome.

**Comment by plietar** [comment] 2017-05-15 22:02
I can now reproduce this thanks to @cortegedusage, looking into it

**Comment by plietar** [comment] 2017-05-15 22:48
Should be fixed now.
Thanks @cortegedusage @angerrit @Seremis @markubiak. Please let me know if you're still having issues.

**Closed as completed** 2017-05-15 22:47 UTC

**Comment by markubiak** [comment] 2017-05-16 00:00
Thanks for the incredibly fast fix!  Everything is working great for me now.

**Comment by cortegedusage** [comment] 2017-05-16 07:13
Thanks a lot!

Op 16 mei 2017 2:00 a.m. schreef "Mark Kubiak" <notifications@github.com>:

**Comment by mgmeedendorp** [comment] 2017-05-16 17:15
Thanks for the quick fix! Everything is working perfectly now
