### ISSUE TITLE
Doesn't start playing anymore

### ISSUE THREAD

**Issue by herrernst** [plietar/librespot#50] opened 2016-02-21 14:53 UTC
With the changes in 3ccb2e2a1035192889033b2fe7f5626787798261, librespot doesn't start playing anymore (iOS just shows "connecting ...").

**Comment by plietar** [comment] 2016-02-22 05:08
I can reproduce this. It seems to be a deadlock between the Player and the SpircManager.
Working on it ...

**Comment by plietar** [comment] 2016-02-22 05:51
Fixed by c700315.

**Closed as completed by plietar** 2016-02-22 05:51 UTC

**Comment by herrernst** [comment] 2016-02-22 12:32
👍
