### ISSUE TITLE
(Raspberry PI) Unusable due to constant underruns

### ISSUE THREAD

**Issue by smoltron** [plietar/librespot#102] opened 2016-07-21 08:30 UTC
I compiled today librespot with rustc 1.10.0 (cfcb716cf 2016-07-03). Compilation went fine without any errors.

Unfortunately the produced executable is unusable with constant underruns.
I ran it with

```
librespot -u xxx -p xxxx --cache /home/xxxx/spotcache --name xxxx -b 320
```

After this the syslog is full of these:

```
Jul 21 11:21:52 raspberrypi librespot[14768]: ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
Jul 21 11:21:52 raspberrypi librespot[14768]: ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
Jul 21 11:21:52 raspberrypi librespot[14768]: ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
Jul 21 11:21:52 raspberrypi librespot[14768]: ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
Jul 21 11:21:52 raspberrypi librespot[14768]: ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
Jul 21 11:21:52 raspberrypi librespot[14768]: ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
```

Playing an mp3 file with mpg123 or a wav file with aplay sound fine and produce no errors.

**Comment by smoltron** [comment] 2016-07-21 08:34
That was a release compilation with `cargo build --release`

**Comment by b-per** [comment] 2016-07-21 22:53
Same issue here. I was using a version of librespot from a few month ago that was working and when I built the new version yesterday with `cargo build --release` I have the same error in the program output, with the sound being distorted

```
TRACE:librespot::stream: allocated stream 12
DEBUG:librespot::audio_file2: Got channel 12
TRACE:librespot::stream: allocated stream 13
DEBUG:librespot::audio_file2: Got channel 13
INFO:librespot::player: Load Done
ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
```

**Comment by alboyer** [comment] 2016-07-21 23:04
I can also confirm this issue. It was caused by 1396f97 and bugs in the portaudio bindings. I have some pending pull requests to the portaudio-rs project and when they are merged I will fix librespot.

**Comment by plietar** [comment] 2016-07-22 23:15
Should be fixed thanks to @alboyer's PR.
@camfrout @smoltron could you confirm please ?

**Closed as completed** 2016-07-22 23:14 UTC

**Comment by b-per** [comment] 2016-07-23 05:26
All good now! Thanks.

**Comment by Bebowi** [comment] 2017-07-17 18:59
Now I've got this issue. I have it on Raspberry Pi and a VM runnig ubuntu. On ubuntu it had been working before. I don't remember me to change something in pulseaudio or any other sound stuff. Any ideas where this is coming from?

**Comment by derWeihnachtsmann** [comment] 2017-07-17 19:18
Did you have updated the system in the last few days?

**Comment by Bebowi** [comment] 2017-07-17 19:21
Yes, I did on both systems. Is there something new making truble?

**Comment by derWeihnachtsmann** [comment] 2017-07-17 20:20
I don't know.. someone should try updating and then build it and/or run it again to test.. try it with a blank new VM if you want.. or build with docker.. perhaps you are getting closer to the problem :-)

**Comment by Bebowi** [comment] 2017-07-17 22:59
Yes you were right. I've installed a new VM and there had been no error. After runnig an update the write underflow occurs. I think the last Ubuntu update did something with pulseaudio.

@alboyer You've just fixed it the last time. Do you have any ideas?
This Error occurs the starting track changes:
```
INFO:librespot::player: Track "Ameno" loaded
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
```
But it is still working. I'm not able to reproduce the error where this message comes in an infinite loop and there are just crackling to hear.

**Comment by montvid** [comment] 2017-09-11 16:55
Same issue with the newest version librespot ddfc28f (2017-08-04). Built on 2017-09-11.
> INFO:librespot::player: Track "Not Alone" loaded
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
ERROR:librespot::audio_backend::portaudio: PortAudio write underflow
INFO:librespot::player: Loading track "Howl"

**Comment by herrernst** [comment] 2017-09-11 19:19
@Bebowi @montvid I know it's not a fix, but a workaround: But if you ALSA output anyway, you can just use the ALSA backend instead of the portaudio one:
`cargo build --no-default-features --features alsa-backend --release`

**Comment by montvid** [comment] 2017-09-11 20:37
@herrernst thank you, seems to work now as expected.
