### ISSUE TITLE
Visible, but wont connect

### ISSUE THREAD

**Issue by gfro84** [plietar/librespot#191] opened 2017-06-04 23:09 UTC
Hi all,

I'm having an issue I wonder if anyone can help me out with. librespot has been working fine for months but alas tonight that is no longer the case. I can see the spotify connect device from within the spotify app, it attempts to connect over the course of ten seconds but fails to do so. 

Running systemctl status when not attempting to connect reveals;
`osmc@osmc:/etc/systemd/system$ systemctl status spotify-connect.service
● spotify-connect.service - Spotify Connect
   Loaded: loaded (/etc/systemd/system/spotify-connect.service; enabled)
   Active: active (running) since Mon 2017-06-05 00:01:43 BST; 4min 8s ago
 Main PID: 716 (librespot)
   CGroup: /system.slice/spotify-connect.service
           └─716 /home/osmc/librespot --name Flange --cache /tmp --bitrate 32...
`
Repeating the command whilst attempting to connect from my phone yields;
`osmc@osmc:/etc/systemd/system$ systemctl status spotify-connect.service
● spotify-connect.service - Spotify Connect
   Loaded: loaded (/etc/systemd/system/spotify-connect.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2017-06-05 00:07:43 BST; 157ms ago
  Process: 716 ExecStart=/home/osmc/librespot --name Flange --cache /tmp --bitrate 320 (code=exited, status=101)
 Main PID: 716 (code=exited, status=101)
`
Any ideas? 

Many thanks

George

**Comment by maxx** [comment] 2017-06-04 23:15
Hey @gfro84,

See: https://github.com/plietar/librespot/issues/190

You'll need to apply this one line update and rebuild.

**Comment by sashahilton00** [comment] 2017-06-04 23:16
Duplicate of #190. @plietar pls close.

**Comment by gfro84** [comment] 2017-06-05 19:45
Thanks very much for the prompt response, and my apologies for raising a duplicate issue.

Best Regards
George

**Comment by sashahilton00** [comment] 2017-06-05 19:46
No problem, thanks.

**Closed as completed** 2017-06-05 19:45 UTC
