### ISSUE TITLE
Example client crashes on songs from offline playlist

### ISSUE THREAD

**Issue by CoDEmanX** [plietar/librespot#28] opened 2015-12-31 17:42 UTC
I can play songs from my playlist with the example client just fine, but if the playlist is available offline, the following error occurs:

> thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `16`)', src\util\spotify_id.rs:45
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value:
> IoError(Error { repr: Os { code: 10053, message: "Eine bestehende Verbindung wurde softwaregesteuert\r\ndurch den Hostcomputer abgebrochen." } })

(An established connection was aborted by the software in your host machine.)

**Comment by plietar** [comment] 2016-01-02 02:33
I remember running into this the other day, but can't reproduce it anymore.
Are you sure it's related to offline playlists ? I can play some fine.
Do you have a link to the problematic playlist ?

**Comment by fbrinker** [comment] 2016-01-10 15:18
I have similar issues but not with an offline playlist.
Played a few tracks from [an online playlist](https://open.spotify.com/user/johanbrook/playlist/2mtlhuFVOFMn6Ho3JmrLc2) without any problems and then suddenly i can't play tracks remotely anymore. After further investigation, it depends on the track that I'm playing...

After starting the application:
- If i play [this track](https://open.spotify.com/track/5FCyoZGaN6nRod1oNDJIWZ), it works every time.
- Switching to [this song](https://open.spotify.com/track/7cdEysgRomnjgMpGomDVyf), it still works
- If I try switching to [this one](https://open.spotify.com/track/31uidLEHAcF8Cw1cX1VCS8), it fails 

All the tracks aren't offline available.

The message i get, when playing the third track, is the following:

```
kMessageTypeLoad *device* *is the hash needed?* 3 0
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `16`)', root/.cargo/git/checkouts/librespot-fc1a303e790f7b1b/master/src/util/spotify_id.rs:46
Chunk 22
Chunk 23
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:688
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:688
Segmentation fault
```

**Comment by fbrinker** [comment] 2016-01-10 15:26
**Small update:**
After investigating further... and assuming `left: 0, right: 16` are the audio channels...

I'm not sure what is happening there, but `assert_eq!(data.len(), 16);` causes the problem (`spotify_id.rs:46`)? I've noticed that the not working track begins with output on the right audio channel only, and after a few seconds both audio channels are used. 

May that cause the problem?

**Comment by CoDEmanX** [comment] 2016-01-15 01:15
The crashes aren't directly related to tracks from offline playlists it seems. All tracks of the following playlist appear to make librespot panic: https://goo.gl/QbfV3j

If I add any of the crashing tracks to a new playlist and download the songs ("make available offline"), then try to play the same tracks but from the new playlist, everything works like a charm! That's pretty odd.

**Comment by CoDEmanX** [comment] 2016-01-15 01:52
I think I figured it out: it crashes on any track in a playlist, if that playlist contains a **local file**.

How did a local file get in there? Well, the Spotify client on Windows indexes local files and you can add them to playlists. The Android client is not able to play them, **unless** you make that playlist available offline - then it will actually download the file from your PC to the phone and you can play it there.

To libspotify, it doesn't matter what track you play, it somehow goes over the list of all tracks in the playlist, won't find a spotify ID for the local track and panic. It should either ignore these entries, or someone would have to add support for local file playback.

**Comment by plietar** [comment] 2016-01-20 10:53
This was fixed by #34 I believe.
For the moment the file is just ignored. I'll have to investigate how the file is transferred between clients later.

**Closed as completed by plietar** 2016-01-20 10:53 UTC

**Comment by CoDEmanX** [comment] 2016-01-20 11:17
Would be pretty cool if librespot could request offline tracks on demand from any available desktop client. It would set it ahead of the Android client.

On the other hand, one could use subsonic or a create a home-made music indexing solution and stream music with librespot from these kind of sources. Spotify would become just one of the sources it could play.

**Comment by sashahilton00** [comment] 2016-01-20 11:23
Would it not be a better idea to implement that separately, along with other ideas such as controlling spotify connect from the reciever? I figure it might be better in terms of compatibility for projects just looking to replace libspotify_embedded with an open source replacement, though i may be alone...

**Comment by realtwister** [comment] 2016-01-20 12:11
maybe we could do something with the conditional compilation of rust http://rustbyexample.com/attribute/cfg.html. Just like the dns-sd problem right now. Or would that be a nightmare to debug? Considering changes need to be compatible with all feature combinations..

Btw. CoDEmanX what you're describing would be more of a application of librespot i think, or do you consider requesting from different spotify clients in the network?
